### ISSUE TITLE
Support for Alan Wake Remastered (version 4) and incorrect font rendering in Quantum Break (version 7)

### ISSUE THREAD

**Issue by romhackingvn** [eprilx/NorthlightFontMaker#1]
Thanks for your tool! I have an error with Alan Wake Remastered
"Unhandled exception. System.Exception: Unsupported version 4
Please make an issue and upload this file
   at NorthlightFontMaker.BINFNTFormat.Load(String inputBINFNT) in D:\a\NorthlightFontMaker\NorthlightFontMaker\NorthlightFontMaker\BINFNT\BINFNTFormat.cs:line 46
   at NorthlightFontMaker.ConverterFunction.ConvertBINFNTtoFNT(String inputBINFNT, String outputFNT) in D:\a\NorthlightFontMaker\NorthlightFontMaker\NorthlightFontMaker\ConverterFunction.cs:line 36
   at NorthlightFontMaker.Program.Main(String[] args) in D:\a\NorthlightFontMaker\NorthlightFontMaker\NorthlightFontMaker\Program.cs:line 138
Press any key to exit..."

 It will be even better if you support Alan Wake Remastered.
[font.zip](https://github.com/eprilx/NorthlightFontMaker/files/7799951/font.zip)

**Comment by eprilx** [comment]
Supported version 4 in [v1.2.0](https://github.com/eprilx/NorthlightFontMaker/releases/tag/1.2.0)

**Comment by romhackingvn** [comment]
> Supported version 4 in [v1.2.0](https://github.com/eprilx/NorthlightFontMaker/releases/tag/1.2.0)

Thank you so much! Can you help me again? I tried working with Quantum Break font, but I have problem with font texture, maybe i saved it with wrong format.
![Screenshot_131](https://user-images.githubusercontent.com/12272584/148011873-eb656c01-0b3a-4a9d-8f30-90a2803104ef.png)
[customer_facing.binfnt.zip](https://github.com/eprilx/NorthlightFontMaker/files/7805545/customer_facing.binfnt.zip)

**Comment by eprilx** [comment]
Looks like from version 7 game can't read BGRA8 format correctly.
Here's the dds file converted to R16_Float with black text on white background (no alpha).
[customer_facing.binfnt_0.zip](https://github.com/eprilx/NorthlightFontMaker/files/7805996/customer_facing.binfnt_0.zip)

**Comment by romhackingvn** [comment]
Thanks, but maybe it not correct, i don't know how.[
![z3081211446178_848542f3bcac14d3ccaa6ba2efe986e5](https://user-images.githubusercontent.com/12272584/148070179-248ec4ea-24a0-4607-9fa6-81cc6740d674.jpg)
](url)
[customer_facing.zip](https://github.com/eprilx/NorthlightFontMaker/files/7808098/customer_facing.zip)

**Comment by eprilx** [comment]
Try again. The background has a different color.
[customer_facing.binfnt.zip](https://github.com/eprilx/NorthlightFontMaker/files/7809193/customer_facing.binfnt.zip)
.

**Comment by romhackingvn** [comment]
Thanks, it's changed! Text display in white will be corrected. Could you help me how to change color?
![z3081828143555_5c2c66d1092116b1016516b76fa429a5](https://user-images.githubusercontent.com/12272584/148143754-83d50e90-b2c5-4a3c-8bee-2ecd68b862c6.jpg)

**Comment by eprilx** [comment]
Just replace the background color to 0x7FFF.
I've made a function to fully convert from RGBA8 to R16F in the tool.
Also it looks like game uses distance fields for font render.
Please test this font because I don't own the game.
[customer_facing.zip](https://github.com/eprilx/NorthlightFontMaker/files/7811791/customer_facing.zip)

**Comment by romhackingvn** [comment]
Thanks, i just tested, i will display like this.
![z3082559935240_0ce7b861382c317eeb5e84331592b412](https://user-images.githubusercontent.com/12272584/148160937-645dbc10-863b-4f72-b7ad-aaaab6b1b4ca.jpg)

**Comment by eprilx** [comment]
It's very aliasing. Here's another font.
[customer_facing.zip](https://github.com/eprilx/NorthlightFontMaker/files/7814139/customer_facing.zip)

**Comment by romhackingvn** [comment]
Hi, it display correctly! <3
![z3083652716962_56e0eac0f0c20c2f1b0e72bd74b44b31](https://user-images.githubusercontent.com/12272584/148205810-603d3f26-d823-4bda-a7b2-4f8d068a0093.jpg)

**Comment by eprilx** [comment]
R16F format is supported and PNG to DDS is automatically converted in [v1.2.1](https://github.com/eprilx/NorthlightFontMaker/releases)
