### ISSUE TITLE
A fatal error occurred. The required library hostfxr.dll could not be found.

### ISSUE THREAD

**Issue by BanhMi939** [eprilx/NorthlightFontMaker#2]
![image](https://user-images.githubusercontent.com/106416065/197170393-df0323b4-becd-4edb-8eed-ffcbfdabdce9.png)
i got this error when trying to convert this font from switch version of alan wake. 
[customer_facing.zip](https://github.com/eprilx/NorthlightFontMaker/files/9838005/customer_facing.zip)

**Comment by eprilx** [comment]
Have you installed .NET 5 runtime yet ?
