### ISSUE TITLE
AW2 Font

### ISSUE THREAD

**Issue by rm-NoobInCoding** [eprilx/NorthlightFontMaker#3]
its version 9
[fixedsys.zip](https://github.com/eprilx/NorthlightFontMaker/files/13197375/fixedsys.zip)

**Comment by eprilx** [comment]
Can you upload more samples ?

**Comment by rm-NoobInCoding** [comment]
sorry game only have this file

**Comment by eprilx** [comment]
This file may just be a debug font for the developer. There are some weird values ​​but editing this font is just useless since we don't see it in the regular game anyway. If the bitmap font exists, it should be customer_facing.binfnt like in other games.

**Comment by rm-NoobInCoding** [comment]
Looks like new version of northlight (which is used for aw2) use ttf/otf font and binfonts are useless.
Maybe next versions will same
